// This file is generated by Sapper — do not edit it!
export const timestamp = 1542015493183;

export const files = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/6d38ebdda90a6b762e46/0.0.js",
	"client/6d38ebdda90a6b762e46/about.about.js",
	"client/6d38ebdda90a6b762e46/blog.blog.js",
	"client/6d38ebdda90a6b762e46/blog_$slug.blog_$slug.js",
	"client/6d38ebdda90a6b762e46/index.index.js",
	"client/6d38ebdda90a6b762e46/main.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ }
];